"""Assemble accepted sections into the final deliverables."""

from __future__ import annotations

import re
from collections import Counter

from . import prompts
from .util import (
    extract_json, mean_score, now_iso, score_text, strip_json_blocks, truncate,
    write_json, write_text,
)

HEADER_COMMENT = re.compile(r"^<!--.*?-->\s*", re.S)


def _clean(section: str) -> str:
    return strip_json_blocks(HEADER_COMMENT.sub("", section)).strip()


def collect_decisions(run, phases: list[dict]) -> list[dict]:
    out: list[dict] = []
    for phase in phases:
        meta = run.phase(phase["id"])
        if not meta.get("section_file"):
            continue
        data = extract_json(run.section_text(phase["id"])) or {}
        decisions = data.get("decisions") if isinstance(data, dict) else []
        for d in decisions if isinstance(decisions, list) else []:
            if not isinstance(d, dict):
                continue
            out.append({
                "id": str(d.get("id", f"D{phase['id']}.?")),
                "phase": phase["id"],
                "phase_title": phase["title"],
                "choice": str(d.get("choice", "")).strip(),
                "why": str(d.get("why", "")).strip(),
                "author": meta.get("author", ""),
            })
    return out


def collect_open_questions(run, phases: list[dict]) -> list[dict]:
    out = []
    for phase in phases:
        data = extract_json(run.section_text(phase["id"])) or {}
        if not isinstance(data, dict):
            continue
        for q in data.get("open_questions") or []:
            out.append({"phase": phase["id"], "title": phase["title"], "question": str(q)})
        for item in data.get("not_covered") or []:
            out.append({
                "phase": phase["id"], "title": phase["title"],
                "question": f"Not covered: {item}",
            })
    return out


def _digest(run, phases: list[dict], per_phase: int = 1800) -> str:
    parts = []
    for phase in phases:
        meta = run.phase(phase["id"])
        if meta.get("status") not in {"accepted", "needs_work"}:
            continue
        body = meta.get("summary") or _clean(run.section_text(phase["id"]))
        parts.append(f"### {phase['id']}. {phase['title']}\n{truncate(body, per_phase)}")
    return "\n\n".join(parts)


def _summary_vendor(run, router) -> str:
    """Give the opening to whichever vendor authored fewer sections."""
    counts = Counter(
        p.get("author") for p in run.data.get("phases", {}).values() if p.get("author")
    )
    pool = router.live or list(router.registry.vendors)
    return min(pool, key=lambda v: counts.get(v, 0))


def build(run, phases: list[dict], router, pool, registry, console,
          write_summary: bool = True) -> dict:
    done = [p for p in phases if run.phase(p["id"]).get("section_file")]
    if not done:
        raise SystemExit("Nothing to assemble yet. Run `python -m claudex run` first.")

    console.head(f"Assembling {len(done)} section(s)")

    # -- executive summary ------------------------------------------------
    opening = ""
    if write_summary:
        vendor = _summary_vendor(run, router)
        assignment = router.assign(
            "assemble", vendor, "deep",
            why=f"{vendor} authored fewer sections, so it writes the neutral opening",
        )
        console.step(f"executive summary by {assignment.label}")
        system, messages = prompts.assemble(run.brief, _digest(run, done))
        try:
            completion = pool.complete(
                vendor=assignment.vendor, tier=assignment.tier,
                system=system, messages=messages,
                max_tokens=2500, temperature=0.5,
            )
            run.record(0, "assemble", assignment, completion, registry)
            opening = completion.text.strip()
        except Exception as exc:
            console.warn(f"executive summary failed: {str(exc)[:120]}")

    decisions = collect_decisions(run, done)
    questions = collect_open_questions(run, done)

    # -- blueprint.md -----------------------------------------------------
    scored = [(p, run.phase(p["id"])) for p in done]
    avg = mean_score([m.get("score") for _, m in scored])
    unscored = [p["id"] for p, m in scored if m.get("score") is None]

    toc = "\n".join(
        f"{i}. [{p['title']}](#{p['id']}-{p['slug']}) "
        f"- {score_text(run.phase(p['id']).get('score'))}/100"
        for i, p in enumerate(done, 1)
    )
    provenance = "\n".join(
        f"| {p['id']} | {p['title']} | {run.phase(p['id']).get('author','-')} | "
        f"{run.phase(p['id']).get('critic','-')} | "
        f"{run.phase(p['id']).get('rounds',0)} | "
        f"{score_text(run.phase(p['id']).get('score'))} |"
        for p in done
    )

    body = [
        f"# {run.name}",
        f"*Blueprint generated by ClaudeX on {now_iso()[:10]} - "
        f"{len(done)} phases, average rubric score {score_text(avg)}/100.*",
        "",
        "> Every section below was written by one model, attacked by a model from a",
        "> different vendor, revised, and scored against a fixed rubric. Scores are the",
        "> models' own judgement of the plan, not evidence that the plan is correct.",
        "",
    ]
    if run.totals().get("cost_is_estimate"):
        body += [
            "> **Offline run.** This blueprint was generated by the deterministic mock",
            "> provider with no API keys. The content is structural placeholder text.",
            "> Set API keys and rerun to get a real design.",
            "",
        ]
    body += [
        "## Project brief",
        run.brief.strip(),
    ]
    if run.constraints.strip():
        body += ["", "## Constraints", run.constraints.strip()]
    if opening:
        body += ["", opening]
    body += [
        "",
        "## Contents",
        toc,
        "",
        "## How each section was produced",
        "",
        "| # | Phase | Author | Critic | Rounds | Score |",
        "|---|-------|--------|--------|--------|-------|",
        provenance,
        "",
        "---",
        "",
    ]

    for phase in done:
        meta = run.phase(phase["id"])
        body.append(f'<a id="{phase["id"]}-{phase["slug"]}"></a>')
        body.append(f"# {phase['id']}. {phase['title']}")
        flag = "" if meta.get("status") == "accepted" else "  **unresolved gaps**"
        body.append(
            f"*score {score_text(meta.get('score'))}/100 - written by {meta.get('author','?')}, "
            f"reviewed by {meta.get('critic','?')}, {meta.get('rounds',0)} round(s){flag}*"
        )
        body.append("")
        body.append(_clean(run.section_text(phase["id"])))
        if gaps := meta.get("blocking_gaps"):
            body.append("")
            body.append("**Unresolved after the final round:**")
            body += [f"- {g}" for g in gaps]
        body.append("")
        body.append("---")
        body.append("")

    if questions:
        body.append("# Open questions for the project owner")
        body.append("")
        body.append("These are the points the models could not settle without you.")
        body.append("")
        for q in questions:
            body.append(f"- **Phase {q['phase']} ({q['title']})** - {q['question']}")
        body.append("")

    blueprint_path = run.dir / "blueprint.md"
    write_text(blueprint_path, "\n".join(body))

    # -- machine-readable side outputs ------------------------------------
    write_json(run.dir / "decisions.json", {
        "project": run.name,
        "generated": now_iso(),
        "average_score": round(avg, 1) if avg is not None else None,
        "unscored_phases": unscored,
        "decisions": decisions,
        "open_questions": questions,
    })

    if questions:
        write_text(
            run.dir / "open-questions.md",
            "# Open questions\n\n"
            + "\n".join(f"- **Phase {q['phase']}** ({q['title']}): {q['question']}" for q in questions)
            + "\n",
        )

    run.data["last_build"] = now_iso()
    run.save()

    console.ok(f"blueprint.md - {len(done)} sections, {len(decisions)} decisions")
    if questions:
        console.ok(f"open-questions.md - {len(questions)} unresolved point(s)")
    return {
        "path": blueprint_path,
        "sections": len(done),
        "decisions": len(decisions),
        "questions": len(questions),
        "average": avg,
    }
