"""The 25-phase blueprint ClaudeX walks a project through.

`profile` drives model tier selection (deep = hardest thinking, light = cheapest).
`depends_on` controls both execution order and what context a phase receives.
Run `claudex init` and edit `config/phases/*.md` to change any of this per project.
"""

PHASES = [
    dict(
        id=1, slug="problem-definition", title="Problem Definition & Requirements",
        profile="deep", depends_on=[],
        goal="Pin down the exact problem, who it is for, and what done means, "
             "so every later phase has a fixed target to aim at.",
        checklist=[
            "Exact problem statement the project solves",
            "Who will use it (primary and secondary audiences)",
            "Why the project is needed now",
            "What is wrong with existing solutions",
            "What the proposed solution improves, concretely",
            "Functional requirements (login, search, upload, prediction, dashboard, notifications)",
            "Non-functional requirements (speed, security, scalability, reliability, usability)",
            "Scope: explicitly in, and explicitly out",
            "Success criteria / KPIs with numeric targets",
            "User roles: User, Admin, Moderator, Developer",
            "User stories and use cases",
        ],
    ),
    dict(
        id=2, slug="feature-planning", title="Feature Planning",
        profile="deep", depends_on=[1],
        goal="Turn requirements into a ranked feature set split into MVP, advanced, and later.",
        checklist=[
            "Core features / MVP cut line",
            "Advanced features", "Admin features", "User profile and settings",
            "Search / filter / sort", "Notifications", "File upload and download",
            "Reports and analytics", "Export PDF / CSV / Excel if needed",
            "Dark and light mode", "Responsive / mobile support", "Accessibility",
            "Error messages", "Loading states", "Empty states", "Confirmation dialogs",
            "Undo / recovery where required", "Recommendation system if relevant",
            "Personalization", "Feedback and rating system", "History / activity tracking",
            "Future feature roadmap",
        ],
    ),
    dict(
        id=3, slug="ui-ux-design", title="UI/UX Design",
        profile="standard", depends_on=[1, 2],
        goal="Define the screens, flows, and design system the frontend will implement.",
        checklist=[
            "Wireframes (described screen by screen)", "User flow", "Dashboard layout",
            "Navigation structure", "Design system", "Fonts, colors, icons",
            "Buttons, forms, cards, modals", "Mobile / tablet / desktop layouts",
            "Accessibility contrast", "Keyboard navigation", "Validation messages",
            "Skeleton / loading UI", "404 and 500 pages", "Onboarding / tutorial",
            "Consistent spacing and components",
        ],
    ),
    dict(
        id=4, slug="frontend", title="Frontend Requirements",
        profile="standard", depends_on=[2, 3],
        goal="Choose the frontend stack and specify its architecture and quality bars.",
        checklist=[
            "Framework: React / Next.js / Angular / other, with justification",
            "Component architecture", "State management", "Routing", "API integration",
            "Authentication handling", "Form validation", "Input sanitization",
            "Error handling", "Lazy loading", "Code splitting", "Caching",
            "Image optimization", "SEO if public website", "Browser compatibility",
            "Responsive testing",
        ],
    ),
    dict(
        id=5, slug="backend", title="Backend Requirements",
        profile="deep", depends_on=[1, 2, 4],
        goal="Specify the server-side stack, APIs, and cross-cutting concerns.",
        checklist=[
            "Backend framework", "REST / GraphQL APIs", "Authentication APIs",
            "Authorization / RBAC", "Business logic", "Database connection",
            "Validation", "Error handling", "Logging", "Rate limiting",
            "Background jobs", "Email / SMS / Telegram notifications", "File storage",
            "API versioning", "Pagination", "Search APIs", "Audit logs",
            "Health-check endpoint",
        ],
    ),
    dict(
        id=6, slug="database", title="Database Design",
        profile="deep", depends_on=[2, 5],
        goal="Produce a concrete schema with keys, relationships, and indexes.",
        checklist=[
            "SQL or NoSQL selection with reasoning", "Tables / collections", "Schema",
            "Primary and foreign keys", "Relationships", "Indexing", "Unique constraints",
            "Validation", "Created / updated timestamps", "Soft delete if required",
            "Database backup", "Database migration", "Encryption for sensitive data",
            "Query optimization",
        ],
    ),
    dict(
        id=7, slug="dataset", title="Dataset Requirements",
        profile="deep", depends_on=[1, 2],
        goal="Define where data comes from and every quality gate it must pass. "
             "Skip gracefully if the project has no AI/ML component.",
        checklist=[
            "Dataset source", "Dataset size", "Number of classes / categories",
            "Features / columns", "Labels", "Data format", "Licensing / permission",
            "Missing values", "Duplicate records", "Corrupted data", "Class imbalance",
            "Outliers", "Noise", "Data cleaning", "Preprocessing",
            "Normalization / scaling", "Encoding categorical values", "Feature engineering",
            "Data augmentation", "Train / validation / test split", "Data leakage checks",
            "Bias checks", "Dataset versioning", "Dataset documentation / data dictionary",
        ],
    ),
    dict(
        id=8, slug="ai-ml-model", title="AI/ML Model Requirements",
        profile="deep", depends_on=[1, 7],
        goal="Choose the modelling approach and the evidence that will prove it works.",
        checklist=[
            "Problem type: classification, regression, recommendation, NLP, CV",
            "Baseline model", "Algorithm selection", "Model architecture",
            "Training pipeline", "Hyperparameter tuning", "Validation strategy",
            "Cross-validation where appropriate", "Accuracy", "Precision", "Recall",
            "F1-score", "ROC-AUC where relevant", "Confusion matrix",
            "MAE / MSE / RMSE for regression",
            "Recommendation metrics: Precision@K / Recall@K / NDCG",
            "Model comparison", "Overfitting / underfitting checks", "Explainability",
            "Confidence score", "Model serialization", "Model versioning",
            "Inference API", "Retraining strategy", "Drift monitoring",
        ],
    ),
    dict(
        id=9, slug="recommendation", title="Recommendation System Requirements",
        profile="standard", depends_on=[7, 8],
        goal="Design the recommender, or state clearly that the project does not need one.",
        checklist=[
            "What will be recommended", "User-based recommendations",
            "Item-based recommendations", "Content-based filtering",
            "Collaborative filtering", "Hybrid recommendations",
            "User interaction tracking", "Likes / clicks / views / history",
            "Ranking algorithm", "Similarity calculation", "Cold-start solution",
            "Trending / popular recommendations", "Personalized recommendations",
            "Feedback loop", "Recommendation explanation (Recommended because...)",
            "Diversity", "Duplicate recommendation prevention", "Recommendation evaluation",
        ],
    ),
    dict(
        id=10, slug="security", title="Security",
        profile="deep", depends_on=[4, 5, 6],
        goal="Cover authentication, authorization, data protection, and OWASP Top 10.",
        checklist=[
            "HTTPS", "Secure authentication", "Password hashing with bcrypt / Argon2",
            "OAuth / Firebase / auth provider if required", "MFA optionally",
            "Role-based authorization", "JWT / session security", "Secure cookies",
            "CSRF protection", "XSS prevention", "SQL / NoSQL injection prevention",
            "Input validation", "Input sanitization", "Rate limiting",
            "Brute-force protection", "CAPTCHA if required", "File upload validation",
            "File-size limits", "Allowed file types", "Virus scanning where required",
            "API key protection", "Secrets in .env", "Never commit secrets to Git",
            "CORS configuration", "Encryption at rest and in transit",
            "Sensitive-data masking", "Password reset security", "Email verification",
            "Account lockout", "Audit logs", "Dependency vulnerability scanning",
            "Security headers", "OWASP Top 10 checks", "Backup and recovery",
            "Privacy / data deletion controls",
        ],
    ),
    dict(
        id=11, slug="testing", title="Testing",
        profile="standard", depends_on=[4, 5, 8, 10],
        goal="Define the test pyramid and the concrete cases that prove each layer works.",
        checklist=[
            "Unit testing", "Integration testing", "API testing", "Database testing",
            "UI testing", "Functional testing", "End-to-end testing", "Regression testing",
            "Smoke testing", "Sanity testing", "Performance testing", "Load testing",
            "Stress testing", "Security testing", "Penetration testing when appropriate",
            "Authentication testing", "Authorization testing", "Input validation testing",
            "Cross-browser testing", "Responsive testing", "Accessibility testing",
            "AI model testing", "Edge-case testing", "Negative testing", "Test cases",
            "Expected vs actual output", "Bug tracking",
        ],
    ),
    dict(
        id=12, slug="edge-cases", title="Important Edge Cases",
        profile="standard", depends_on=[4, 5, 11],
        goal="Enumerate failure modes and the exact behaviour the system must show for each.",
        checklist=[
            "Empty input", "Very large input", "Wrong input type", "Duplicate data",
            "No internet", "Slow internet", "API timeout", "Server unavailable",
            "Database unavailable", "Expired login / session", "Invalid token",
            "Unauthorized access", "User refreshes during process",
            "Multiple simultaneous requests", "File too large", "Unsupported file",
            "AI unable to predict confidently", "No recommendation available",
            "Zero search results",
        ],
    ),
    dict(
        id=13, slug="performance", title="Performance",
        profile="standard", depends_on=[4, 5, 6, 8],
        goal="Set numeric performance budgets and the techniques that will hit them.",
        checklist=[
            "Page load time", "API response time", "Database query speed",
            "AI inference speed", "Caching", "CDN", "Compression", "Pagination",
            "Lazy loading", "Optimized assets", "Database indexes",
            "Background processing", "Queue system where required",
            "Memory and CPU usage", "Concurrent-user testing",
        ],
    ),
    dict(
        id=14, slug="scalability", title="Scalability",
        profile="standard", depends_on=[5, 6, 13],
        goal="Describe what changes at 10, 1,000, and 100,000 users.",
        checklist=[
            "10 users to 1,000 to 100,000 users", "Horizontal scaling", "Load balancing",
            "Database scaling", "Redis / cache", "Message queues",
            "Microservices only if required", "CDN", "Cloud storage", "Autoscaling",
            "Stateless backend design where appropriate",
        ],
    ),
    dict(
        id=15, slug="api-design", title="API Design",
        profile="standard", depends_on=[5, 6],
        goal="Specify every endpoint with request, response, and status codes.",
        checklist=[
            "Clear endpoint naming", "GET / POST / PUT / PATCH / DELETE",
            "Request schema", "Response schema", "HTTP status codes", "Authentication",
            "Authorization", "Validation", "Pagination", "Filtering", "Sorting",
            "Error response format", "Rate limits",
            "API documentation using Swagger / OpenAPI",
        ],
    ),
    dict(
        id=16, slug="devops", title="DevOps & Deployment",
        profile="standard", depends_on=[4, 5, 6, 10],
        goal="Define environments, CI/CD, and how a release actually ships and rolls back.",
        checklist=[
            "Git / GitHub", "Branch strategy", "Gitignore rules", "Environment variables",
            "Development environment", "Testing / staging environment",
            "Production environment", "CI/CD", "Automated tests", "Docker if useful",
            "Cloud deployment", "Domain name", "SSL", "Database hosting",
            "File / object storage", "Production secrets", "Deployment rollback",
            "Backup strategy",
        ],
    ),
    dict(
        id=17, slug="monitoring", title="Monitoring",
        profile="light", depends_on=[13, 16],
        goal="Decide what is watched in production and what triggers an alert.",
        checklist=[
            "Application logs", "Error tracking", "Server health", "CPU / RAM monitoring",
            "API latency", "Database performance", "Failed login monitoring",
            "Model performance", "User activity", "Uptime monitoring", "Alerts",
            "Crash reporting",
        ],
    ),
    dict(
        id=18, slug="analytics", title="Analytics",
        profile="light", depends_on=[1, 2, 17],
        goal="Tie product metrics back to the KPIs from phase 1.",
        checklist=[
            "Number of users", "Active users", "Feature usage", "Conversion",
            "Session duration", "Search queries", "Recommendation clicks",
            "AI prediction usage", "Error rate", "Retention",
            "Admin analytics dashboard",
        ],
    ),
    dict(
        id=19, slug="documentation", title="Documentation",
        profile="standard", depends_on=[1, 4, 5, 6, 7, 8, 15, 16],
        goal="Specify every document the project ships with, and its outline.",
        checklist=[
            "README", "Project introduction", "Problem statement", "Objectives",
            "Features", "Technology stack", "Architecture diagram", "Database schema",
            "Dataset description", "ML methodology", "API documentation",
            "Installation steps", "Environment-variable guide", "Deployment steps",
            "Testing details", "Security measures", "Screenshots", "Demo video",
            "Known limitations", "Future scope", "Contributors",
        ],
    ),
    dict(
        id=20, slug="diagrams", title="Project Diagrams",
        profile="standard", depends_on=[5, 6, 8, 15],
        goal="Produce every diagram as valid Mermaid source so it renders anywhere.",
        checklist=[
            "System architecture diagram", "Use-case diagram", "Data-flow diagram",
            "ER diagram", "Class diagram if required", "Sequence diagram",
            "Activity diagram", "Deployment diagram", "AI/ML pipeline diagram",
            "User-flow diagram",
        ],
    ),
    dict(
        id=21, slug="research", title="Project Research",
        profile="deep", depends_on=[1],
        goal="Survey what already exists and state honestly how this project differs. "
             "Mark any specific claim that needs verification instead of inventing citations.",
        checklist=[
            "Existing systems", "Competitor analysis", "Research papers",
            "Existing datasets", "Existing APIs", "Similar GitHub projects",
            "Industry solutions", "Limitations of current solutions",
            "Why your project is different",
        ],
    ),
    dict(
        id=22, slug="legal-privacy", title="Legal & Privacy",
        profile="standard", depends_on=[7, 10, 21],
        goal="Cover licensing, consent, and data-handling obligations.",
        checklist=[
            "Dataset license", "Open-source licenses", "API terms of service",
            "User consent", "Privacy policy if necessary", "Terms and conditions",
            "Cookie handling", "Personal-data storage", "Data retention",
            "User-data deletion", "Copyright checks",
        ],
    ),
    dict(
        id=23, slug="code-quality", title="Project Quality",
        profile="light", depends_on=[4, 5, 11],
        goal="Set the engineering standards the codebase is held to.",
        checklist=[
            "Clean folder structure", "Meaningful variable names", "Reusable components",
            "Comments only where useful", "No hard-coded secrets", "No unused code",
            "No console errors", "Proper error handling", "Proper loading states",
            "Consistent API responses", "Code formatting", "ESLint / linter",
            "Modular architecture",
        ],
    ),
    dict(
        id=24, slug="final-evaluation", title="Final Evaluation",
        profile="deep", depends_on=[1, 8, 10, 11, 13, 14, 16],
        goal="Audit the whole blueprint against the original problem and answer every "
             "question honestly, including where the plan is still weak.",
        checklist=[
            "Does the project solve the original problem?",
            "Are all promised features working?", "Are there critical bugs?",
            "Is it secure?", "Is it responsive?", "Is performance acceptable?",
            "Does AI actually outperform the baseline?", "Is data quality acceptable?",
            "Can another developer run the project?", "Can it recover from failures?",
            "Is it deployable?", "Can it scale?",
            "Can you explain every architectural decision?",
        ],
    ),
    dict(
        id=25, slug="presentation", title="Presentation / Viva",
        profile="standard", depends_on=[1, 7, 8, 11, 21, 24],
        goal="Write the actual script and prepared answers for a demo or viva.",
        checklist=[
            "30-second project introduction", "Problem statement",
            "Why you selected the problem", "Existing solution", "Your solution",
            "Architecture", "Tech stack", "Dataset", "Model / algorithm",
            "Feature demo", "Security", "Testing", "Results", "Limitations",
            "Future improvements",
            "Q: Why did you choose this technology?",
            "Q: What happens if traffic increases?",
            "Q: How do you secure user data?",
            "Q: How did you evaluate your model?",
            "Q: What is unique about your project?",
        ],
    ),
]

BY_ID = {p["id"]: p for p in PHASES}
